"""
verification/kernel_adapter.py

Bridges the operator-agnostic per-call numeric checker (_check_one_call)
to KernelBench's problem/candidate convention.

A problem file defines Model, get_inputs(), get_init_inputs(). Calls are
GENERATED by calling those functions n_trials times. The candidate's
calling convention (ModelNew class vs KernelAgent's kernel_function) is
resolved via a small registry.

REMOVED: TritonBench-G ("split_file") support -- the file-splitting,
test-body-execution, call-spying adapter for TritonBench-G's
separator-delimited files. Deliberately deleted, not deprecated in
place, once KernelBench became the sole real-corpus validation target;
see git history if TritonBench-G evaluation is ever needed again rather
than resurrecting a parallel unused code path.

EXTENDING:
  - New candidate convention (e.g. a third kernel-generation system's
    output format): subclass CandidateConvention, implement detect()
    and build_candidate_fn(), add it to CANDIDATE_CONVENTIONS. Nothing
    else in this file changes.

KNOWN UNVERIFIED PIECE: KernelFunctionConvention's weight-argument
ordering (see its docstring). Confirm against a real composed
kernel_function artifact before trusting those results.
"""

import importlib.util
import multiprocessing as mp
import os
import tempfile
import traceback
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Optional

import torch

from verification.layer2_numeric_oracle.perturbation import check_perturbation_tolerance
from verification.layer1_structural.runtime_guards import check_determinism
from verification.layer3_properties.kernelbench_operator_registry import resolve_operator_key
from verification.layer3_properties.attention_batched_properties import (
    try_attention_layer3,
)
from verification.layer3_properties.layernorm_generic_properties import (
    try_layernorm_layer3,
)
from verification.layer3_properties.matmul_generic_properties import (
    try_matmul_layer3,
)
from verification.layer3_properties.softmax_generic_properties import (
    try_softmax_layer3,
)
from verification.layer3_properties.rmsnorm_generic_properties import (
    try_rmsnorm_layer3,
)


# ---------------------------------------------------------------------------
# Shared low-level helpers
# ---------------------------------------------------------------------------

def _load_module(path_or_src: str, tag: str, from_source: bool) -> dict:
    """Write src to a REAL temp .py file and import it via importlib, so
    reference/candidate (which likely define same-named functions/kernels)
    don't collide as Python module-cache entries."""
    if from_source:
        src = path_or_src
    else:
        with open(path_or_src, "r", encoding="utf-8") as f:
            src = f.read()

    tmp_dir = tempfile.gettempdir()
    fname = f"_ka_{tag}_{uuid.uuid4().hex}.py"
    fpath = os.path.join(tmp_dir, fname)
    with open(fpath, "w", encoding="utf-8") as f:
        f.write(src)

    spec = importlib.util.spec_from_file_location(fname[:-3], fpath)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.__dict__


def _to_device(args, device: str) -> list:
    """Move every tensor in `args` to `device`, passing non-tensor
    elements (ints, floats, etc. -- e.g. groupnorm's num_groups) through
    unchanged."""
    return [a.to(device) if isinstance(a, torch.Tensor) else a for a in args]


def _first_tensor(args: tuple, kwargs: dict) -> Optional[torch.Tensor]:
    for a in args:
        if isinstance(a, torch.Tensor):
            return a
    for v in kwargs.values():
        if isinstance(v, torch.Tensor):
            return v
    return None


def _check_one_call(
    candidate_fn: Callable,
    reference_fn: Callable,
    args: tuple,
    kwargs: dict,
    skip_shape_guessed_layer3: bool = False,
) -> dict:
    """
    Universal, signature-agnostic checks for one call -- works for any
    (*args, **kwargs), which is what lets this generalize across
    operators and across problem shapes without a per-operator KernelSpec.
    This is the canonical copy; nothing else in the repo should
    reimplement it.

    skip_shape_guessed_layer3: set True when the caller already knows
    the operator's identity for certain (e.g. via
    kernelbench_operator_registry) and is about to run that operator's
    real algebraic_properties separately. Without this, the shape-based
    try_*_layer3 guessers below still run unconditionally and can
    misfire on a KNOWN operator whose call shape happens to collide with
    a different operator's heuristic (e.g. InstanceNorm's (x, weight,
    bias) matching layernorm's "x plus two 1-D tensors matching x's
    trailing dim" pattern whenever W == C) -- a false failure from the
    wrong operator's property getting merged into a correctly-identified
    call's result. Known identity should override guessing, not run
    alongside it.
    """
    out: dict[str, Any] = {"passed": True, "checks": {}}

    try:
        cand_out = candidate_fn(*args, **kwargs)
    except Exception as e:
        out["passed"] = False
        out["checks"]["executes"] = (False, f"{type(e).__name__}: {e}")
        return out
    out["checks"]["executes"] = (True, "ran without exception")

    try:
        ref_out = reference_fn(*args, **kwargs)
    except Exception as e:
        out["checks"]["reference_executes"] = (False, f"{type(e).__name__}: {e}")
        out["checks"]["note"] = "reference itself failed on these captured args -- cannot compare"
        return out

    if isinstance(cand_out, torch.Tensor) and isinstance(ref_out, torch.Tensor):
        shape_ok = cand_out.shape == ref_out.shape
        out["checks"]["shape_match"] = (
            shape_ok, f"candidate {tuple(cand_out.shape)} vs reference {tuple(ref_out.shape)}"
        )
        if not shape_ok:
            out["passed"] = False
            return out

        dtype_ok = cand_out.dtype == ref_out.dtype
        out["checks"]["dtype_match"] = (dtype_ok, f"{cand_out.dtype} vs {ref_out.dtype}")
        if not dtype_ok:
            out["passed"] = False

        finite_input = all(
            (not isinstance(a, torch.Tensor)) or torch.isfinite(a).all()
            for a in args
        ) and all(
            (not isinstance(v, torch.Tensor)) or torch.isfinite(v).all()
            for v in kwargs.values()
        )

        if not finite_input:
            cand_nan_mask = torch.isnan(cand_out) | torch.isinf(cand_out)
            ref_nan_mask = torch.isnan(ref_out) | torch.isinf(ref_out)
            pattern_matches = torch.equal(cand_nan_mask, ref_nan_mask)
            out["checks"]["nan_inf"] = (
                pattern_matches,
                "input non-finite; candidate/reference non-finite pattern match" if pattern_matches
                else "input non-finite, but candidate and reference disagree on WHERE -- real discrepancy"
            )
            if not pattern_matches:
                out["passed"] = False
                return out

            allclose_ok = torch.allclose(
                cand_out.float(), ref_out.float(), atol=1e-3, rtol=1e-2, equal_nan=True
            )
            out["checks"]["allclose"] = (
                allclose_ok,
                "matches (NaN-aware comparison; raw max_err is undefined when NaNs are present)"
                if allclose_ok else "mismatch on finite elements despite matching non-finite pattern"
            )
            if not allclose_ok:
                out["passed"] = False

            out["checks"]["perturbation_tolerance"] = (
                None, "skipped -- not meaningful on non-finite input"
            )
            out["checks"]["determinism"] = (
                None, "skipped -- not meaningful on non-finite input (torch.equal fails on identical NaNs)"
            )

        else:
            finite_ok = torch.isfinite(cand_out).all().item()
            out["checks"]["nan_inf"] = (finite_ok, "finite" if finite_ok else "contains NaN/Inf")
            if not finite_ok:
                out["passed"] = False
                return out

            allclose_ok = torch.allclose(cand_out.float(), ref_out.float(), atol=1e-3, rtol=1e-2)
            max_err = (cand_out.float() - ref_out.float()).abs().max().item()
            out["checks"]["allclose"] = (allclose_ok, f"max_err={max_err:.6f}")
            if not allclose_ok:
                out["passed"] = False

            primary = _first_tensor(args, kwargs)
            if primary is not None:
                def _cand_perturbed(x, _a=args, _k=kwargs):
                    new_args = tuple(x if a is primary else a for a in _a)
                    new_kwargs = {k: (x if v is primary else v) for k, v in _k.items()}
                    return candidate_fn(*new_args, **new_kwargs)

                def _ref_perturbed(x, _a=args, _k=kwargs):
                    new_args = tuple(x if a is primary else a for a in _a)
                    new_kwargs = {k: (x if v is primary else v) for k, v in _k.items()}
                    return reference_fn(*new_args, **new_kwargs)

                try:
                    p_ok, p_detail = check_perturbation_tolerance(_cand_perturbed, _ref_perturbed, primary)
                    out["checks"]["perturbation_tolerance"] = (p_ok, p_detail)
                    if p_ok is False:
                        out["passed"] = False
                except Exception as e:
                    out["checks"]["perturbation_tolerance"] = (False, f"check errored: {e}")
                    out["passed"] = False

            if len(args) == 1 and not kwargs:
                try:
                    det_ok, det_detail = check_determinism(lambda x: candidate_fn(x), args[0])
                    out["checks"]["determinism"] = (det_ok, det_detail)
                    if not det_ok:
                        out["passed"] = False
                except Exception as e:
                    out["checks"]["determinism"] = (False, f"check errored: {e}")
            else:
                out["checks"]["determinism"] = (
                    None, "skipped -- multi-arg/keyword signature not retrofitted for determinism check"
                )

        if not skip_shape_guessed_layer3:
            attn_result = try_attention_layer3(candidate_fn, args, kwargs)
            if attn_result is not None:
                out["checks"].update(attn_result)
                if any(v[0] is False for v in attn_result.values()):
                    out["passed"] = False

            ln_result = try_layernorm_layer3(candidate_fn, reference_fn, args, kwargs)
            if ln_result is not None:
                out["checks"].update(ln_result)
                if any(v[0] is False for v in ln_result.values()):
                    out["passed"] = False

            mm_result = try_matmul_layer3(candidate_fn, reference_fn, args, kwargs)
            if mm_result is not None:
                out["checks"].update(mm_result)
                if any(v[0] is False for v in mm_result.values()):
                    out["passed"] = False

            sm_result = try_softmax_layer3(candidate_fn, args, kwargs)
            if sm_result is not None:
                out["checks"].update(sm_result)
                if any(v[0] is False for v in sm_result.values()):
                    out["passed"] = False

            rn_result = try_rmsnorm_layer3(candidate_fn, reference_fn, args, kwargs)
            if rn_result is not None:
                out["checks"].update(rn_result)
                if any(v[0] is False for v in rn_result.values()):
                    out["passed"] = False

    else:
        out["checks"]["note"] = (
            "candidate/reference did not both return a torch.Tensor "
            f"(cand={type(cand_out).__name__}, ref={type(ref_out).__name__}); "
            "tensor-shaped checks skipped for this call -- only 'executes' verified."
        )

    return out


# ---------------------------------------------------------------------------
# Unified result type
# ---------------------------------------------------------------------------

@dataclass
class AdapterResult:
    problem_file: str
    candidate_file: str = "<inline>"
    candidate_format: Optional[str] = None   # convention name (modelnew | kernel_function)
    resolved_operator: Optional[str] = None  # matched key from kernelbench_operator_registry, if any
    load_error: Optional[str] = None
    suspected_leak: Optional[str] = None
    trial_checks: list = field(default_factory=list)

    @property
    def allclose_pass(self) -> Optional[bool]:
        if self.load_error or not self.trial_checks:
            return None
        return all(t["checks"].get("allclose", (False, ""))[0] for t in self.trial_checks)

    @property
    def checker_pass(self) -> Optional[bool]:
        if self.load_error or not self.trial_checks:
            return None
        return all(t["passed"] for t in self.trial_checks)

    @property
    def is_gap(self) -> bool:
        """The case the paper cares about: naive testing says fine, checker disagrees."""
        return self.allclose_pass is True and self.checker_pass is False


# ---------------------------------------------------------------------------
# KernelBench candidate convention registry
# ---------------------------------------------------------------------------

class CandidateConvention:
    """Base class for a KernelBench-style candidate calling convention.
    Add a new one by subclassing, implementing detect()/build_candidate_fn(),
    and registering it in CANDIDATE_CONVENTIONS -- nothing else changes."""
    name = "base"

    @classmethod
    def detect(cls, cand_ns: dict) -> bool:
        raise NotImplementedError

    @classmethod
    def build_candidate_fn(cls, cand_ns: dict, ref_model, init_args: tuple, device: str) -> Callable:
        raise NotImplementedError


class ModelNewConvention(CandidateConvention):
    """Raw KernelBench convention: class ModelNew(nn.Module)."""
    name = "modelnew"

    @classmethod
    def detect(cls, cand_ns: dict) -> bool:
        return "ModelNew" in cand_ns and isinstance(cand_ns["ModelNew"], type)

    @classmethod
    def build_candidate_fn(cls, cand_ns: dict, ref_model, init_args: tuple, device: str) -> Callable:
        # FIXED: cand_model used to stay on whatever device __init__
        # happened to allocate it on (CPU by default) while the actual
        # forward() call receives inputs moved to `device` by
        # _run_model_based -- for a real load_inline CUDA-kernel
        # ModelNew this means the kernel launch dereferences a CPU
        # tensor's pointer from device code (illegal memory access, or
        # silently reads garbage), confirmed via a real run: every check
        # downstream got either a CUDA illegal-access error or wildly
        # wrong "allclose" numbers -- on the REFERENCE candidate too,
        # since nothing anywhere in this file ever called .to(device).
        cand_model = cand_ns["ModelNew"](*init_args).to(device)

        def candidate_fn(*args, _m=cand_model):
            return _m(*args)

        return candidate_fn


class KernelFunctionConvention(CandidateConvention):
    """
    KernelAgent's ComposerAgent output: a top-level kernel_function(...).

    UNVERIFIED: kernel_function is stateless, so weights the reference
    Model holds as nn.Parameters must be passed explicitly. The order
    assumed here is named_parameters() registration order -- a guess,
    not a confirmed convention. Open a real composed artifact's own
    self-test call site and confirm before trusting results; a wrong
    order looks identical to a real correctness bug.
    """
    name = "kernel_function"

    @classmethod
    def detect(cls, cand_ns: dict) -> bool:
        return "kernel_function" in cand_ns and callable(cand_ns["kernel_function"])

    @classmethod
    def build_candidate_fn(cls, cand_ns: dict, ref_model, init_args: tuple, device: str) -> Callable:
        kernel_fn = cand_ns["kernel_function"]
        # weight_args inherit ref_model's device -- ref_model is already
        # moved to `device` by _run_model_based before this is called.
        weight_args = tuple(p.detach() for _, p in ref_model.named_parameters())

        def candidate_fn(*args, _fn=kernel_fn, _w=weight_args):
            return _fn(*args, *_w)

        return candidate_fn


CANDIDATE_CONVENTIONS: list[type[CandidateConvention]] = [
    ModelNewConvention,
    KernelFunctionConvention,
]


def _check_leak(candidate_src: str) -> Optional[str]:
    """
    Cheap textual leak check for the ModelNew convention specifically --
    NOT a substitute for manual review, and does not cover
    kernel_function (no reliable textual signal known for a
    kernel_function that just calls the reference internally instead of
    launching a real kernel).
    """
    flat = candidate_src.replace(" ", "")
    suspicious = []
    if "classModelNew(Model)" in flat:
        suspicious.append("ModelNew subclasses Model directly")
    if "ModelNew=Model" in flat:
        suspicious.append("ModelNew is a bare alias for Model")
    return "; ".join(suspicious) if suspicious else None


def _run_known_operator_properties(operator_key: str, candidate_fn: Callable, call_args: tuple) -> dict:
    """
    Loads verification/specs/<operator_key>.py, calls get_spec(), and
    runs every entry in spec.algebraic_properties directly against this
    captured call -- reuses the EXACT same property functions
    run_checker.py uses via KernelChecker, no duplicated logic. Returns
    a dict of {check_name: (bool, detail)}, same shape _check_one_call
    already produces for Layers 1/2, so results merge cleanly.

    operator_key with NO matching spec file is a legitimate, silent
    no-op (empty dict, zero checks) -- registering an operator in
    kernelbench_operator_registry.py under a key that intentionally
    doesn't match any verification/specs/*.py file is how a caller
    opts an operator OUT of the shape-guessed try_*_layer3 detectors
    (see resolve_operator_key's callers: operator_key is not None is
    what sets skip_shape_guessed_layer3) without needing an existing
    per-operator spec whose candidate_fn calling convention might not
    match -- e.g. a KernelBench-format layernorm candidate takes only
    (x,), not the TritonBench spec's (x, gamma, beta). A spec file that
    DOES exist but fails to load or run is still a real failure, not
    silenced -- only "no such file" is treated as "nothing to check."
    """
    spec_path = f"verification/specs/{operator_key}.py"
    if not os.path.exists(spec_path):
        return {}

    try:
        spec_module_spec = importlib.util.spec_from_file_location(f"_spec_{operator_key}", spec_path)
        spec_module = importlib.util.module_from_spec(spec_module_spec)
        spec_module_spec.loader.exec_module(spec_module)
        spec = spec_module.get_spec()
    except Exception as e:
        return {f"known_operator_spec_load[{operator_key}]": (False, f"{type(e).__name__}: {e}")}

    # FIXED: single-tensor specs (SingleTensorSpec-based -- softmax,
    # swish, gelu, ...) expect `inputs` to be the bare tensor itself,
    # matching SingleTensorSpec.primary_input's own convention (inputs
    # IS the tensor, not a 1-tuple wrapping it); multi-arg specs
    # (matmul, layernorm, ...) expect the tuple as-is, which already
    # matches call_args unchanged. Passing call_args as a raw tuple
    # unconditionally used to crash every single-arg operator's
    # known-operator properties with AttributeError ('tuple' object has
    # no attribute 'contiguous'/'shape'/...) -- confirmed via a real
    # run: matmul (2-arg) was unaffected, softmax/swish/gelu (1-arg)
    # failed every property check this way, every trial.
    prop_inputs = call_args[0] if len(call_args) == 1 else call_args

    results = {}
    for prop_name, prop_fn in spec.algebraic_properties:
        try:
            outcome = prop_fn(candidate_fn, prop_inputs)
            if isinstance(outcome, (list, tuple)):
                ok, detail = bool(outcome[0]), str(outcome[1]) if len(outcome) > 1 else None
            else:
                ok, detail = bool(outcome), None
            results[f"known_operator[{operator_key}]_{prop_name}"] = (ok, detail)
        except Exception as e:
            results[f"known_operator[{operator_key}]_{prop_name}"] = (
                False, f"property check errored: {type(e).__name__}: {e}"
            )
    return results


def _run_model_based(problem_path: str, candidate_src: str, n_trials: int) -> AdapterResult:
    result = AdapterResult(problem_file=problem_path)

    operator_key = resolve_operator_key(Path(problem_path).stem)
    result.resolved_operator = operator_key

    leak = _check_leak(candidate_src)
    if leak:
        result.suspected_leak = leak

    try:
        ref_ns = _load_module(problem_path, tag="reference", from_source=False)
    except Exception as e:
        result.load_error = f"reference load failed: {type(e).__name__}: {e}"
        return result

    for name in ("Model", "get_inputs", "get_init_inputs"):
        if name not in ref_ns:
            result.load_error = f"reference missing required '{name}' -- not a KernelBench-format file"
            return result

    try:
        cand_ns = _load_module(candidate_src, tag="candidate", from_source=True)
    except Exception as e:
        # A bad CUDA compile (load_inline failure) surfaces here -- treat
        # compile failure as a checker FAIL, not a silent skip: a kernel
        # that doesn't compile is a correctness failure by definition.
        result.load_error = f"candidate load/compile failed: {type(e).__name__}: {e}"
        return result

    convention = None
    for candidate_cls in CANDIDATE_CONVENTIONS:
        if candidate_cls.detect(cand_ns):
            convention = candidate_cls
            break

    if convention is None:
        known = ", ".join(c.name for c in CANDIDATE_CONVENTIONS)
        result.load_error = (
            f"candidate matches none of the known conventions ({known}) -- "
            "unrecognized format, call-accuracy failure"
        )
        return result

    result.candidate_format = convention.name

    ModelRef = ref_ns["Model"]
    get_inputs = ref_ns["get_inputs"]
    get_init_inputs = ref_ns["get_init_inputs"]

    # FIXED: nothing in this function used to move models or inputs to
    # CUDA -- get_inputs()/get_init_inputs() return plain CPU tensors
    # (matches real KernelBench problem files, which never call .cuda()
    # themselves; KernelBench's own eval.py does the device placement
    # centrally instead, see its load_original_model_and_inputs /
    # eval_kernel_against_ref). Without it, a real load_inline
    # CUDA-kernel ModelNew launches its kernel against a CPU tensor's
    # pointer -- confirmed via a real run: illegal memory access errors,
    # or wildly wrong numeric output, on BOTH reference and candidate,
    # for every operator.
    device = "cuda" if torch.cuda.is_available() else "cpu"

    for trial in range(n_trials):
        try:
            init_args = _to_device(get_init_inputs(), device)
            call_args = _to_device(get_inputs(), device)
            ref_model = ModelRef(*init_args).to(device)

            def reference_fn(*args, _m=ref_model):
                return _m(*args)

            candidate_fn = convention.build_candidate_fn(cand_ns, ref_model, init_args, device)

            record = _check_one_call(
                candidate_fn, reference_fn, tuple(call_args), {},
                skip_shape_guessed_layer3=(operator_key is not None),
            )

            if operator_key is not None:
                known_checks = _run_known_operator_properties(operator_key, candidate_fn, tuple(call_args))
                record["checks"].update(known_checks)
                if any(v[0] is False for v in known_checks.values()):
                    record["passed"] = False

            record["call_index"] = trial
            result.trial_checks.append(record)
        except Exception as e:
            result.trial_checks.append({
                "call_index": trial,
                "passed": False,
                "checks": {"trial_setup": (False, f"{type(e).__name__}: {e}")},
            })

    return result


# ---------------------------------------------------------------------------
# Dispatch
# ---------------------------------------------------------------------------

def run_candidate(problem_path: str, candidate_src: str, n_trials: int = 5) -> AdapterResult:
    return _run_model_based(problem_path, candidate_src, n_trials)


def _worker(problem_path: str, candidate_src: str, n_trials: int, queue: mp.Queue):
    try:
        result = run_candidate(problem_path, candidate_src, n_trials)
        queue.put(("OK", result))
    except Exception as e:
        queue.put(("ERROR", f"{type(e).__name__}: {e}\n{traceback.format_exc(limit=3)}"))


def run_with_timeout(
    problem_path: str,
    candidate_src: str,
    n_trials: int = 5,
    timeout_seconds: int = 120,
) -> AdapterResult:
    """
    120s default: KernelBench candidates routinely compile CUDA
    extensions via load_inline on first run, and a cold nvcc compile
    alone can eat 30-60s before a single check runs.
    """
    ctx = mp.get_context("spawn")
    queue = ctx.Queue()
    p = ctx.Process(target=_worker, args=(problem_path, candidate_src, n_trials, queue))
    p.start()
    p.join(timeout=timeout_seconds)

    if p.is_alive():
        p.kill()
        p.join()
        return AdapterResult(problem_file=problem_path, load_error=f"TIMEOUT after {timeout_seconds}s")

    if queue.empty():
        return AdapterResult(problem_file=problem_path, load_error="subprocess exited with no result (crash?)")

    status, payload = queue.get()
    if status == "ERROR":
        return AdapterResult(problem_file=problem_path, load_error=f"subprocess error: {payload}")
    return payload
