"""
Layer 2 -- SCOPE-DIVERGENCE DETECTOR (opt-in, default OFF).

Flags invocations where the perturbation check's own guarantee probably does
not hold, so that a tolerance computed in a regime the theorem does not cover
is *labelled* rather than silently trusted.

  KCC_SCOPE_DETECT=1              enable
  KCC_SCOPE_GRAM_SAMPLES=<int>    deltas used for the Gram probe (default 20)
  KCC_SCOPE_RECORD_ALL=1          also emit a record for invocations that are
                                  IN scope, carrying their raw signals

DEFAULT OFF. When on it is **purely additive**: it appends a record and never
touches `passed`. See "Why annotate and not act" below -- that is a designed
property, not an oversight.

---------------------------------------------------------------------------
WHAT IS BEING DETECTED
---------------------------------------------------------------------------
`../adaptive_tol_theory_2026-08-25/GPU_NATIVE.md` established, natively on
Triton kernels, that the bound holds for operators that are C^1 at the
evaluation point with a perturbation response **above the float32 quantisation
floor** and **below the onset of saturation** -- and it identified exactly
three ways out of that envelope:

  1. STRUCTURAL      index-valued output, J = 0 almost everywhere.
                     `argmax`, `argmin`. No measurement needed or possible;
                     these are excluded by the shape of the operator.
  2. NONLINEARITY    the measured response is not the one the operator's own
                     Jacobian generates (softmax saturating to a hard select
                     is the motivating instance). Detected by the GRAM SCREEN
                     below.
  3. FP FLOOR        the response is smaller than the spacing of the output's
                     own floating-point representation, so the check is
                     measuring representable-number granularity rather than
                     ||J d||. Signature: s/ulp of order 1.

---------------------------------------------------------------------------
THE GRAM SCREEN (2026-08-27) -- AND THE DEFECT SCREEN IT REPLACES
---------------------------------------------------------------------------
The theorem's whole content is that in scope the sensitivity sample is

    s_k  =  || f(x + d_k) - f(x) ||_inf  ~=  || J d_k ||_inf

i.e. the sample's entire distribution is a functional of the Jacobian Gram
matrix J J^T (theory_audit_2026-08-27 H1; extended to input-dependent
Jacobians in adaptive_tol_theory_2026-08-25/attention_gram/). The screen
tests exactly that statement, delta by delta:

    r_k = s_k / || J d_k ||_inf,      J d_k  by float64 forward-mode autodiff
                                      (torch.func.jvp) of the operator's MATH
                                      definition (math_refs.py) at the
                                      invocation's own input, along the SAME
                                      d_k the tolerance was built from.

    signal = median_k log10(r_k);   flag when |signal| >= log10(2).

This is a PAIRED comparison -- same delta on both sides -- so the 40-sample
draw noise that dominates distributional versions of the Gram law (+-8% per
draw, attention_gram round) cancels entirely. In scope, every r_k is 1 up to
(a) curvature at the delta scale (banked <=0.1% on ordinary inputs, and the
worst adversarial in-scope invocation ever measured reached ~10-15%
homogeneity defect) and (b) fp32 measurement noise, bounded by the floor gate
below to a few percent. Out of scope the measured response is generated by
something other than J -- flips of a saturated select, higher-order terms
around a vanishing derivative, or a reference kernel computing a different
function than its spec -- and r_k leaves the curvature band.

THE THRESHOLD IS PRE-REGISTERED, NOT FITTED: factor 2 in either direction
(|log10 r| >= 0.30103). It sits >= 4x above the worst measured in-scope
curvature band in log space, and anything the screen is worth flagging --
mechanism-(2) cases whose measured tolerances were wrong by 9.5x-343x -- must
deviate by far more than 2x. If the corpus shows out-of-scope cases inside
the factor-2 band, the screen is falsified and the verdict must say so; the
threshold is not to be nudged to make a run pass (that rule is inherited from
the defect screen's post-mortem, below).

WHAT THIS REPLACES. The first saturation screen was the two-scale
linearisation defect |s(1) - s(0.1)/0.1| / s(1) >= 10%. It was FALSIFIED on
the 2026-08-26 corpus run: in-scope invocations legitimately reach 9.6%
(cross_entropy/adversarial_large_magnitude_logits) while the least
out-of-scope saturation case sat at 6.6% -- the classes overlap and no
threshold separates them (verification_runs/scope_detect_2026-08-26/
FINDINGS.md Section 2). The failure is structural, not a tuning problem: the
ladder tests self-consistency ALONG ONE RAY, and any positively-homogeneous
response -- linear or not -- passes it exactly. theory_audit_2026-08-27
Section 2 exhibits the witness: flash_attention/wrong_causal_mask with ladder
defect 0.0012 and CV 5.496, an impossible combination for a Gaussian max.
The Gram screen compares against the TRUE derivative instead of against the
response's own scaling, which is precisely the information the ladder cannot
see. The defect screen's code has been REMOVED, not re-tuned; its banked
falsification stands and must not be re-litigated by reintroducing a
defect-percentage threshold.

SCOPE OF THE FLAG. A Gram fire means "the measured sensitivity is not
explained by the operator's Jacobian at this input". That covers saturation
AND a reference kernel that computes a different function than the math
definition (the attention_gram round found a real padded-column bug exactly
this way). The record cannot distinguish the two by itself; adjudication is a
human step, and both conditions genuinely invalidate the tolerance's
guarantee, so flagging both is correct behaviour.

REJECTED SIGNALS, recorded so they are not re-proposed:

  * The linearisation-defect ladder. Falsified as above. Do not resurrect.
  * Coefficient of variation of the sensitivity sample. The `CV <= 0.7555`
    ceiling is a correct property of the linear regime (it is the sharp
    half-normal bound, theory_audit_2026-08-27 Section 2) but is not a usable
    screen: `skip_rescaling` is out of scope with CV 0.080, BELOW every
    in-scope variant, and across 5 seeds one variant's CV ranged 0.080-3.333.
  * Peak attention weight. Reaches 1.000 on 6 of 9 non-primary variants, two
    of which are fully in scope. Falsified on 5-seed native measurement.

---------------------------------------------------------------------------
THE FLOOR SCREEN AND ITS THRESHOLD (unchanged -- validated 2026-08-26)
---------------------------------------------------------------------------
  s/ulp = s / ulp(max |f(x)|)     ulp taken at the OUTPUT's magnitude

  median(s/ulp) < 32     out-of-scope worst 3.00 | in-scope least 360
                         geometric midpoint 32.9, margin 11x either side

Corpus-validated: silent-set margins 9x-381x, zero classification changes
across probe-size arms, catches all three fp-floor variants on every
invocation. **The s/ulp statistic is the MEDIAN and that is load-bearing.**
`cross_entropy` is fully in scope yet its MINIMUM s/ulp over 40 samples is
2.0 -- numerically identical to the fp-floor variants this screen exists to
catch. On the minimum the two classes overlap and no threshold can separate
them; on the median they separate by 120x.

The floor gate is also what makes the Gram screen's measured side readable:
below the floor, s_k is quantisation, not response, and r_k would be
meaningless. The Gram screen therefore only runs when median(s/ulp) >= 32;
below that the floor screen owns the record.

---------------------------------------------------------------------------
WHY ANNOTATE AND NOT ACT
---------------------------------------------------------------------------
This records a flag and changes nothing else. The alternatives were considered
and rejected on the evidence:

  * WIDENING THE TOLERANCE on a flag would lose catches, and there is no
    defensible width to widen to. In the flagged regimes the tolerance is not
    merely imprecise, it is measuring the wrong quantity -- and it errs in BOTH
    directions: `skip_rescaling` yields an inflated L = 343 from ulp-floor
    differences, while `equal_attention_weights` is clamped to the 1e-6 floor
    and is far too tight. A correction with no known sign is not a correction.
  * ROUTING TO EXTRA ADVERSARIAL CHECKS spends runtime and adds new
    false-positive surface, on a signal that has never been run against the
    corpus.
  * FAILING THE CANDIDATE is plainly wrong: an out-of-scope tolerance is a
    statement about the CHECK, not about the kernel.

A safety net that changes verdicts is not a safety net; it is a new failure
mode. This project has twice found that a control it never fired cannot
license a behaviour change (`../n_samples_curve_2026-08-25/`), so the flag
earns its verdict authority only after a corpus run shows what it fires on.

RNG DISCIPLINE. The screen draws NO randomness: it reuses the sensitivity
loop's own deltas, and the JVP is deterministic float64 arithmetic on CPU.
Arm A (detector off) and arm B (detector on) therefore consume the torch
generators identically and must produce byte-identical verdicts; any
difference is a wiring bug, not a finding.
"""

import math
import os
import torch

from verification.layer2_numeric_oracle import math_refs as _mrefs

_ENABLED = os.environ.get("KCC_SCOPE_DETECT") == "1"

# 20 deltas. The 2026-08-26 round measured convergence of a median-over-deltas
# statistic on this corpus: 20-delta and 40-delta arms disagreed on 0 of 854
# records while 3 disagreed with 40 on 18. The Gram median inherits that
# choice; the per-delta log-ratios are recorded raw so a later pass can
# re-derive the needed count offline instead of re-measuring.
_GRAM_SAMPLES = int(os.environ.get("KCC_SCOPE_GRAM_SAMPLES", "20"))

# KCC_SCOPE_RECORD_ALL=1 -- emit the record even when nothing fired.
#
# This exists for CALIBRATION, and it is what makes the corpus validation
# answerable. Without it a run can only report WHICH invocations fired; it
# cannot report how much headroom the silent operators had, so "no false
# alarms" would be indistinguishable from "no false alarms, by 1%".
_RECORD_ALL = os.environ.get("KCC_SCOPE_RECORD_ALL") == "1"

# Floor threshold: derived 2026-08-26 (geometric midpoint, 11x margins) and
# corpus-validated the same day. Gram threshold: pre-registered factor 2 --
# see the module docstring; NOT derived from any class separation, and not to
# be nudged toward one.
SULP_MIN_MEDIAN = 32.0
GRAM_MAX_ABS_LOG10 = math.log10(2.0)

# Fewer valid ratios than this and the Gram signal is withheld rather than
# reported from a handful of directions. Valid means: finite measured s_k,
# finite nonzero ||J d_k||, both above zero.
GRAM_MIN_VALID = 5

REASON_STRUCTURAL = "structural_exclusion"
REASON_GRAM = "gram_divergence"
REASON_FP_FLOOR = "quantisation_floor"
REASON_TOL_FLOOR = "tolerance_floor_bound"


def ulp_at(magnitude, dtype=torch.float32):
    """Spacing of `dtype` at `magnitude`, computed exactly rather than as an
    eps-times-magnitude approximation.

    Exactness matters at the threshold: the fp-floor variants sit at s/ulp of
    2-3, so a 2x error in `ulp` moves them across a boundary that in-scope
    operators clear by 11x but these do not clear at all.
    """
    m = abs(float(magnitude))
    if m == 0.0 or not math.isfinite(m):
        return None
    t = torch.tensor(m, dtype=dtype)
    nxt = torch.nextafter(t, torch.tensor(float("inf"), dtype=dtype))
    u = float(nxt - t)
    return u if u > 0 else None


def sulp_median(sensitivities_t, ref_base):
    """Median of s/ulp, with ulp taken at the output's own magnitude.

    Median, not minimum -- see the module docstring. This single choice is what
    keeps `cross_entropy` (in scope, min s/ulp 2.0, median 360) out of the
    flagged set.
    """
    if sensitivities_t is None or sensitivities_t.numel() == 0:
        return None
    try:
        mag = float(ref_base.abs().max())
    except Exception:
        return None
    dt = ref_base.dtype if ref_base.is_floating_point() else torch.float32
    u = ulp_at(mag, dt)
    if u is None:
        return None
    vals = sorted(float(v) / u for v in sensitivities_t.tolist())
    return vals[len(vals) // 2]


def _to_cpu64(t):
    """Float tensors to CPU float64; everything else (int companions such as
    cross_entropy targets, plain Python scalars) unchanged apart from device."""
    if torch.is_tensor(t):
        if t.is_floating_point():
            return t.detach().to(device="cpu", dtype=torch.float64)
        return t.detach().to(device="cpu")
    return t


def measure_gram(op_name, x, companions, deltas, s_meas):
    """Per-delta paired comparison of the measured sensitivity against the
    exact directional derivative of the operator's math definition.

    Costs len(deltas) float64 JVPs on CPU and NO kernel launches, NO device
    RNG, and NO GPU work at all -- the tensors are copied off-device once.

    Returns a dict of raw signals, or None when the operator has no registered
    math definition or the JVP cannot be evaluated. Declining is fail-open:
    no signal, no flag -- the same direction structural_l.py declines in.
    """
    fn = _mrefs.get(op_name)
    if fn is None or not deltas:
        return None
    try:
        x64 = _to_cpu64(x)
        comps = tuple(_to_cpu64(c) for c in companions)
        f = lambda t: fn(t, *comps)
        logs = []
        n_skipped = 0
        for d, s in zip(deltas, s_meas):
            s = float(s)
            try:
                _, jd = torch.func.jvp(f, (x64,), (_to_cpu64(d),))
            except Exception:
                n_skipped += 1
                continue
            s_lin = float(jd.abs().max())
            if not (math.isfinite(s) and math.isfinite(s_lin)) \
                    or s <= 0.0 or s_lin <= 0.0:
                n_skipped += 1
                continue
            logs.append(math.log10(s / s_lin))
        if len(logs) < GRAM_MIN_VALID:
            return {"log10_median": None, "log10_ratios": logs,
                    "n_valid": len(logs), "n_skipped": n_skipped}
        srt = sorted(logs)
        return {"log10_median": srt[len(srt) // 2],
                "log10_ratios": logs,
                "n_valid": len(logs), "n_skipped": n_skipped}
    except Exception:
        return None


def classify(gram_log10_med, sulp_med, output_is_discrete, tol_at_floor):
    """Apply the rule. Returns a list of reason dicts, possibly empty.

    The two measured screens are OR'd, not AND'd, because they detect
    different mechanisms: Gram divergence shows the response escaping the
    Jacobian at an ordinary s/ulp, while the fp floor shows a tiny s/ulp.
    Requiring both would miss each. (In practice the floor gate in
    build_record means a floor-flagged record has no Gram signal at all.)
    """
    reasons = []

    if output_is_discrete:
        # No measurement involved and none possible: J = 0 a.e., so assumption
        # A3 fails by the shape of the operator. Reported at every input.
        reasons.append({
            "reason": REASON_STRUCTURAL, "severity": "excluded",
            "detail": "index-valued output: J = 0 almost everywhere (A3 fails); "
                      "perturbation tolerance is not defined for this operator",
        })
        return reasons

    if sulp_med is not None and sulp_med < SULP_MIN_MEDIAN:
        reasons.append({
            "reason": REASON_FP_FLOOR, "severity": "diverged",
            "detail": f"median s/ulp = {sulp_med:.2f} < {SULP_MIN_MEDIAN:.0f}: the "
                      f"perturbation response is at float32 granularity, so the "
                      f"tolerance reflects representable-number spacing rather "
                      f"than the Jacobian",
        })

    if gram_log10_med is not None and abs(gram_log10_med) >= GRAM_MAX_ABS_LOG10:
        reasons.append({
            "reason": REASON_GRAM, "severity": "diverged",
            "detail": f"median measured/Jacobian sensitivity ratio = "
                      f"10^{gram_log10_med:+.3f} (threshold 2x either way): the "
                      f"response is not the one the operator's Jacobian "
                      f"generates at this input, so the first-order bound does "
                      f"not describe the tolerance (saturation, or the "
                      f"reference computing a different function than the "
                      f"math definition)",
        })

    if tol_at_floor:
        # Advisory, not a divergence. GPU_NATIVE.md Section 4: the theorem
        # bounds 3*sigma*q95(s), but the shipped tolerance is
        # max(3*sigma*q95(s), 1e-6). When the clamp binds, the upper side of
        # the sandwich can be violated by the clamp alone.
        reasons.append({
            "reason": REASON_TOL_FLOOR, "severity": "advisory",
            "detail": "adaptive_tol is clamped at the 1e-6 absolute floor; the "
                      "bound is stated for the unclamped quantile",
        })

    return reasons


def build_record(sensitivities_t, ref_base, reference_fn, x, deltas,
                 adaptive_tol, op_name=None, companions=()):
    """Compute the signals and return one scope record, or None.

    Returns None when the detector is off or has nothing to say, so the caller
    can append unconditionally. `reference_fn` is accepted for interface
    stability but no longer called: the Gram screen replaced the defect
    probe's s(0.1) reference launches with CPU JVPs of the math definition.
    """
    if not _ENABLED:
        return None

    discrete = not ref_base.is_floating_point()

    sulp = None
    gram = None
    if not discrete and sensitivities_t is not None:
        sulp = sulp_median(sensitivities_t, ref_base)
        # Floor gate: below the floor the measured side is quantisation and
        # the ratio is unreadable; the floor screen owns those records.
        if deltas and sulp is not None and sulp >= SULP_MIN_MEDIAN:
            k = max(1, min(_GRAM_SAMPLES, len(deltas)))
            gram = measure_gram(op_name, x, companions, deltas[:k],
                                sensitivities_t[:k].tolist())

    tol_at_floor = adaptive_tol is not None and adaptive_tol <= 1e-6

    g_med = gram.get("log10_median") if gram else None
    reasons = classify(g_med, sulp, discrete, tol_at_floor)
    diverged = [r for r in reasons if r["severity"] != "advisory"]
    if not reasons and not _RECORD_ALL:
        return None

    return {
        "kind": "scope_divergence",
        "op": op_name,
        # False only when a screen actually fired. An advisory-only record
        # (tolerance clamped at the floor) leaves the invocation in scope.
        "in_scope": not diverged,
        "reasons": reasons,
        # Raw signals travel with the verdict so a later round can re-threshold
        # offline from a banked run instead of re-measuring on a GPU.
        "gram_log10_median": g_med,
        "gram_log10_ratios": (gram or {}).get("log10_ratios"),
        "gram_n_valid": (gram or {}).get("n_valid"),
        "gram_n_skipped": (gram or {}).get("n_skipped"),
        "sulp_median": sulp,
        "adaptive_tol": float(adaptive_tol) if adaptive_tol is not None else None,
        "thresholds": {"gram_max_abs_log10": GRAM_MAX_ABS_LOG10,
                       "sulp_min_median": SULP_MIN_MEDIAN,
                       "gram_samples": _GRAM_SAMPLES},
    }
